#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

/*
* Approximates the value of pi. 
*
* Author: Jonathon Gebhardt
* Class: CS4900-B90
* Instructor: Dr. John Nehrbass
* Assignment: Homework 2 
* GitHub: 
*
* Requirements:
*   - Number of cpus used
*   - Total run time
*   - Smallest value of epsilon
*   - Best estimate of pi
*   - Number of iterations before converging
*   - Values of M (numbers inside the circle) and N (number of points 
*     generated)
*
* Challenge:
*   - What is the optimal value for P, where P is the number of points 
*     generated by each node?
*/

void showUsage();

int main(int argc, char *argv[])
{
    int opt, numPoints, epsilon;

    numPoints = -1, epsilon = -1;

    // TODO: Should also check that numPoints and epsilon don't equal -1 
    // after this loop.
    while((opt = getopt(argc, argv, "n:e:")) != -1)
    {
        switch(opt)
        {
            case 'n':
                numPoints = atoi(optarg);
                break;
            case 'e':
                epsilon = atoi(optarg);
                break;
            case '?':
                showUsage();
                break;
        }
    }

    if(numPoints == 0)
    {
        fprintf(stderr, "Error: invalid parameter '-n'\n");
        showUsage();
        return 1;
    }

    if(epsilon == 0)
    {
        fprintf(stderr, "Error: invalid parameter '-e'\n");
        showUsage();
        return 1;
    }

    // Using system time as a seed instead of rank to avoid deterministic
    // number generation (i.e., each series of randomly generated numbers
    // would be identical).
    srand(time(0));

    // TODO: epsilon shouldn't govern the random number, 
    // the boundary of the square should.
    // These random numbers are completely deterministic.
    double x, y;
    x = (double)rand() / (double)RAND_MAX; 
    y = rand() % epsilon;

    printf("Randomly generated (x, y): (%f, %f)\n", x, y);

    // Area of a square: 4r^2
    // Area of a circle: (pi)r^2
    // Ratio of a circle to the square: (pi)/4
    
    // Pick n random points (x, y), bound by the square
    
    // Count the number of points inside the circle -> M
   
    // 4(M/N) will converge to (pi) as a sufficient 
    // number of points are selected

    // x^2 + y^2 < r^2

    return 0;
}

void showUsage()
{
    printf("showing usage...\n");
}
